// //firebase_options.dart

// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAfXDyvkSnLJUZzk4mcEiaO1TwIJHzJHb4',
//     appId: '1:668877109522:web:977287e38d1fa60bc39bcb',
//     messagingSenderId: '668877109522',
//     projectId: 'user-management-be5cb',
//     authDomain: 'user-management-be5cb.firebaseapp.com',
//     storageBucket: 'user-management-be5cb.firebasestorage.app',
//     measurementId: 'G-H0M2K4XG1V',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCiHdVYEbmeHFwsb7GQnJ9fpmoqTnYzPMA',
//     appId: '1:668877109522:android:a011bc5c6c594e7dc39bcb',
//     messagingSenderId: '668877109522',
//     projectId: 'user-management-be5cb',
//     storageBucket: 'user-management-be5cb.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyA3zOmTlxrGui507oloNapGevhoLyLp-HA',
//     appId: '1:668877109522:ios:148781808232350fc39bcb',
//     messagingSenderId: '668877109522',
//     projectId: 'user-management-be5cb',
//     storageBucket: 'user-management-be5cb.firebasestorage.app',
//     iosBundleId: 'com.example.userManagement',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyA3zOmTlxrGui507oloNapGevhoLyLp-HA',
//     appId: '1:668877109522:ios:148781808232350fc39bcb',
//     messagingSenderId: '668877109522',
//     projectId: 'user-management-be5cb',
//     storageBucket: 'user-management-be5cb.firebasestorage.app',
//     iosBundleId: 'com.example.userManagement',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAfXDyvkSnLJUZzk4mcEiaO1TwIJHzJHb4',
//     appId: '1:668877109522:web:b6185842e4affe8bc39bcb',
//     messagingSenderId: '668877109522',
//     projectId: 'user-management-be5cb',
//     authDomain: 'user-management-be5cb.firebaseapp.com',
//     storageBucket: 'user-management-be5cb.firebasestorage.app',
//     measurementId: 'G-XK5MX0SM32',
//   );
// }
